import type { IndustrySlug } from "./types";

export type IndividualIndustryPage = {
  slug: string;
  parentSlug: IndustrySlug;
  name: string;
  metaTitle: string;
  metaDescription: string;
  h1: string;
  intro: string;
  fit: string;
  problems: string[];
  scanChecks: string[];
  baseImprovements: string[];
  proAutomations: string[];
  discoveryNotes: string[];
  guideLinks: { href: string; label: string }[];
};

const baseGuideLinks = [
  { href: "/guides/website-trust-signals", label: "Website trust signals" },
  { href: "/guides/social-proof-and-local-conversion", label: "Social proof and local conversion" },
  { href: "/guides/ai-search-local-businesses", label: "AI search for local businesses" },
];

export const INDIVIDUAL_INDUSTRY_PAGES: Record<string, IndividualIndustryPage> = {
  plumbers: {
    slug: "plumbers",
    parentSlug: "home-services",
    name: "Plumbers",
    metaTitle: "Local SEO and visibility for plumbers | GravyBlock",
    metaDescription: "Help your plumbing company get more calls from Google profile visibility, stronger trust signals, and faster conversion paths.",
    h1: "Plumbers: earn more local calls before emergency jobs go elsewhere",
    intro: "Plumbing demand is often urgent. Customers choose whoever looks trustworthy, nearby, and easy to reach in seconds.",
    fit: "GravyBlock helps plumbing teams tighten profile accuracy, website conversion clarity, review trust, and AI-ready facts tied to one local business context.",
    problems: [
      "Service areas are vague or inconsistent across profile and site.",
      "After-hours messaging does not match real dispatch availability.",
      "Phone-first mobile paths are buried under generic marketing copy.",
    ],
    scanChecks: [
      "Google profile and listing consistency signals.",
      "Website trust, conversion, and contact friction indicators.",
      "Review and social proof patterns visible from public pages.",
    ],
    baseImprovements: ["Monthly readiness refresh and score updates.", "Monthly summary of listing, trust, and conversion drift.", "Ongoing trend history for one plumbing business profile."],
    proAutomations: ["Faster recurring refreshes.", "Execution queues for content, citations, and review-oriented work where supported.", "Expanded workspace automation coverage."],
    discoveryNotes: ["Google profile accuracy affects emergency and near-me decisions.", "Website trust signals reduce call hesitation.", "Reviews and AI summaries shape who gets called first."],
    guideLinks: [{ href: "/guides/local-seo-for-home-services", label: "Local SEO for home services" }, ...baseGuideLinks],
  },
  electricians: {
    slug: "electricians",
    parentSlug: "home-services",
    name: "Electricians",
    metaTitle: "Local visibility and trust for electricians | GravyBlock",
    metaDescription: "Improve electrician lead flow from Google profile, website trust, reviews, and local conversion readiness.",
    h1: "Electricians: become the trusted local choice for urgent and planned work",
    intro: "Electrical work is high-trust and high-stakes. Prospects compare licensing cues, reviews, and response speed quickly.",
    fit: "GravyBlock gives electricians a practical visibility and trust baseline: profile completeness, conversion clarity, and recurring performance checks.",
    problems: ["Category and service details do not match real jobs taken.", "License and trust indicators are hard to find on mobile.", "Inconsistent business facts weaken local and AI discovery."],
    scanChecks: ["Profile/service clarity checks.", "Website trust and CTA readiness signals.", "Reputation and social-presence context."],
    baseImprovements: ["Monthly listing and website check cadence.", "Recurring visibility summaries.", "Priority tracking over time."],
    proAutomations: ["More frequent checks and queue-driven execution support.", "Deeper workspace automation where available."],
    discoveryNotes: ["Google profile quality drives map visibility.", "Website conversion clarity turns visibility into calls.", "AI summaries favor consistent entity details."],
    guideLinks: [{ href: "/guides/local-seo-for-home-services", label: "Local SEO for home services" }, ...baseGuideLinks],
  },
  "hvac-companies": {
    slug: "hvac-companies",
    parentSlug: "home-services",
    name: "HVAC companies",
    metaTitle: "Local SEO for HVAC companies and contractors | GravyBlock",
    metaDescription: "HVAC visibility, trust, and conversion support for map searches, seasonal demand, and recurring local growth.",
    h1: "HVAC companies: capture seasonal demand with cleaner local signals",
    intro: "HVAC buyers compare urgency response, financing clarity, and trust proof before they call.",
    fit: "GravyBlock helps HVAC operators align profile data, service messaging, and conversion paths so demand spikes turn into booked jobs.",
    problems: ["Seasonal messaging conflicts across profile and site.", "Weak trust proof around certifications and warranties.", "Conversion paths are slow on mobile during urgent weather events."],
    scanChecks: ["Profile consistency and service-intent coverage.", "Website conversion and trust indicators.", "Public proof and discovery signal quality."],
    baseImprovements: ["Monthly monitoring of visibility and trust shifts.", "Recurring summaries and trend tracking."],
    proAutomations: ["Faster refresh and expanded execution queues.", "Additional automation coverage for ongoing local growth work."],
    discoveryNotes: ["Google profile signals influence near-me decisions.", "Website trust and CTA clarity increase calls/bookings.", "AI engines cite coherent, repeated facts."],
    guideLinks: [{ href: "/guides/local-seo-for-home-services", label: "Local SEO for home services" }, ...baseGuideLinks],
  },
  roofers: {
    slug: "roofers",
    parentSlug: "home-services",
    name: "Roofers",
    metaTitle: "Local visibility for roofers and roofing companies | GravyBlock",
    metaDescription: "Help roofing businesses improve profile trust, local conversion, and recurring visibility performance.",
    h1: "Roofers: build local trust before storm-season buyers choose",
    intro: "Roofing decisions involve high spend and low trust tolerance. Local clarity and proof matter.",
    fit: "GravyBlock helps roofers spot credibility gaps between listings, site content, and public trust cues, then monitor them over time.",
    problems: ["Service area and office details feel unclear.", "Before/after proof is thin or outdated.", "Website CTAs do not support urgent inspections cleanly."],
    scanChecks: ["Listing consistency and profile readiness.", "Trust and conversion checks on your website.", "Reputation and social proof indicators."],
    baseImprovements: ["Monthly checks and visibility summaries.", "Trend tracking for trust and conversion signals."],
    proAutomations: ["Faster recurring checks and queue-based support.", "Broader ongoing automation where configured."],
    discoveryNotes: ["Profile trust signals reduce skepticism.", "Website trust cues improve quote conversion.", "AI answers amplify consistent facts and proof."],
    guideLinks: [{ href: "/guides/local-seo-for-home-services", label: "Local SEO for home services" }, ...baseGuideLinks],
  },
  dentists: {
    slug: "dentists",
    parentSlug: "health-wellness",
    name: "Dentists",
    metaTitle: "Local SEO and trust signals for dentists | GravyBlock",
    metaDescription: "Dental practices can improve map visibility, profile trust, website conversion, and patient-ready local signals.",
    h1: "Dentists: improve visibility and trust before patients book",
    intro: "Dental patients compare reviews, provider clarity, and booking confidence quickly.",
    fit: "GravyBlock helps dental teams align profile facts, website trust, and conversion pathways so visibility turns into real appointments.",
    problems: ["Provider and hours info drifts across channels.", "Insurance and payment clarity is weak.", "Booking CTAs and forms create friction."],
    scanChecks: ["Profile consistency and local discovery indicators.", "Website trust and conversion readiness.", "Public review and social-presence signals."],
    baseImprovements: ["Monthly scan-based monitoring and trend updates.", "Recurring summaries for visibility and trust."],
    proAutomations: ["Higher refresh cadence and additional queue workflows.", "Expanded automation coverage where supported."],
    discoveryNotes: ["Google profile quality drives local patient discovery.", "Website trust affects booking confidence.", "AI summaries rely on consistent provider/service facts."],
    guideLinks: [{ href: "/guides/local-seo-for-dentists", label: "Local SEO for dentists" }, ...baseGuideLinks],
  },
  chiropractors: {
    slug: "chiropractors",
    parentSlug: "health-wellness",
    name: "Chiropractors",
    metaTitle: "Local visibility for chiropractors | GravyBlock",
    metaDescription: "Help chiropractic clinics strengthen Google profile trust, website conversion, reviews, and AI-search visibility.",
    h1: "Chiropractors: earn trust in local search before the first consult",
    intro: "Patients evaluate credibility quickly. Clear services and trust signals decide who gets booked.",
    fit: "GravyBlock helps chiropractic practices find and fix visibility and trust gaps across listings, website, and social proof signals.",
    problems: ["Service descriptions are generic and unclear.", "Review themes do not reflect treatment strengths.", "Website contact and booking flows create friction."],
    scanChecks: ["Profile and category signal checks.", "Website trust and conversion checks.", "Review and social presence quality cues."],
    baseImprovements: ["Monthly check cadence and readiness summaries.", "Ongoing trend insight for one business profile."],
    proAutomations: ["Faster refresh, broader queue support, deeper automation."],
    discoveryNotes: ["Profile clarity influences map discovery.", "Website trust drives booking confidence.", "AI answers prefer consistent, specific service descriptions."],
    guideLinks: baseGuideLinks,
  },
  "med-spas": {
    slug: "med-spas",
    parentSlug: "health-wellness",
    name: "Med spas",
    metaTitle: "Local growth visibility for med spas | GravyBlock",
    metaDescription: "Med spas can improve local discovery with stronger profile consistency, trust signals, and conversion-ready websites.",
    h1: "Med spas: turn local discovery into higher-intent consults",
    intro: "Aesthetic buyers compare proof, trust, and clarity fast. Inconsistent details weaken confidence.",
    fit: "GravyBlock helps med spas tighten listing consistency, website trust cues, and review credibility while monitoring drift over time.",
    problems: ["Services and provider context are inconsistent.", "Before/after proof is disconnected from booking flows.", "Trust and policy details are hard to find."],
    scanChecks: ["Profile consistency and service visibility checks.", "Website trust and CTA friction checks.", "Public proof and discovery signal patterns."],
    baseImprovements: ["Monthly monitoring and prioritization summaries.", "Trend tracking for visibility and conversion readiness."],
    proAutomations: ["Faster recurring checks and more execution queue support.", "Expanded automation layer where configured."],
    discoveryNotes: ["Google profile quality impacts high-intent local searches.", "Website trust signals improve consult conversion.", "AI search favors consistent service and provider context."],
    guideLinks: baseGuideLinks,
  },
  lawyers: {
    slug: "lawyers",
    parentSlug: "professional-services",
    name: "Lawyers",
    metaTitle: "Local SEO and trust for lawyers and law firms | GravyBlock",
    metaDescription: "Law firms can improve local visibility, intake conversion, and profile trust without fake ranking promises.",
    h1: "Lawyers: strengthen local visibility and intake trust",
    intro: "Legal buyers compare credibility and response quality quickly. Local profile trust and website clarity are critical.",
    fit: "GravyBlock helps law firms tighten local profile signals, intake conversion pathways, and reputation readiness with recurring monitoring.",
    problems: ["Practice area messaging is too broad.", "Office and contact facts are inconsistent.", "Intake routes are unclear on mobile."],
    scanChecks: ["Profile consistency and local readiness.", "Website trust and conversion checks.", "Public reputation signal coverage."],
    baseImprovements: ["Monthly readiness updates and summaries.", "Trend tracking for listing and trust stability."],
    proAutomations: ["Faster recurring checks and expanded queue workflows.", "Deeper automation support in workspace."],
    discoveryNotes: ["Google profile trust influences local legal discovery.", "Website conversion clarity affects consultation volume.", "AI summaries reward specific, consistent firm facts."],
    guideLinks: [{ href: "/guides/local-seo-for-law-firms", label: "Local SEO for law firms" }, ...baseGuideLinks],
  },
  accountants: {
    slug: "accountants",
    parentSlug: "professional-services",
    name: "Accountants",
    metaTitle: "Local visibility and conversion for accountants and CPAs | GravyBlock",
    metaDescription: "Help accounting firms improve local profile clarity, website trust, and lead conversion signals.",
    h1: "Accountants: improve local trust before tax and advisory inquiries",
    intro: "Accounting buyers want clear expertise, clear process, and confidence their inquiry will be handled professionally.",
    fit: "GravyBlock helps accounting teams align local profile signals, website trust, and review credibility into one recurring readiness view.",
    problems: ["Service lines are unclear between tax and advisory.", "Profile and website details drift during seasonality.", "Inquiry forms and CTAs do not qualify leads well."],
    scanChecks: ["Profile consistency and visibility indicators.", "Website trust and conversion checks.", "Public social proof and review signal cues."],
    baseImprovements: ["Monthly checks and summary monitoring.", "Trend history to catch drift over time."],
    proAutomations: ["Higher refresh cadence and broader queue workflows.", "Expanded automation support where available."],
    discoveryNotes: ["Profile quality affects local professional-service discovery.", "Website trust improves form-fill and call quality.", "AI engines summarize firms with strong entity consistency."],
    guideLinks: baseGuideLinks,
  },
  florists: {
    slug: "florists",
    parentSlug: "local-retail",
    name: "Florists",
    metaTitle: "Local visibility for florists and flower shops | GravyBlock",
    metaDescription: "Florists can improve local search and conversion with better profile clarity, trust signals, and faster contact paths.",
    h1: "Florists: win local flower orders with clearer trust and delivery signals",
    intro: "Florist demand is often event-driven and time-sensitive. Clarity around availability and delivery matters.",
    fit: "GravyBlock helps flower shops improve listing quality, website conversion, and public trust signals that influence fast purchase decisions.",
    problems: ["Delivery area and cutoff times are inconsistent.", "Website and profile messaging diverges by season.", "Urgent ordering paths are hard to find on mobile."],
    scanChecks: ["Listing and profile consistency checks.", "Website trust and conversion readiness checks.", "Review and social proof visibility indicators."],
    baseImprovements: ["Monthly readiness updates and trend tracking.", "Recurring summaries to keep seasonal drift in check."],
    proAutomations: ["Faster recurring checks and execution queues.", "Broader automation coverage where supported."],
    discoveryNotes: ["Google profile clarity affects near-me order capture.", "Website trust and speed improve checkout intent.", "AI summaries rely on consistent business details."],
    guideLinks: baseGuideLinks,
  },
  "auto-repair-shops": {
    slug: "auto-repair-shops",
    parentSlug: "auto-trade",
    name: "Auto repair shops",
    metaTitle: "Local visibility for auto repair shops | GravyBlock",
    metaDescription: "Auto repair businesses can improve local discovery, trust, and call conversion with profile and website clarity.",
    h1: "Auto repair shops: convert map searches into booked service",
    intro: "Drivers compare trust and turnaround quickly. Local profile quality and website credibility are decisive.",
    fit: "GravyBlock gives auto repair teams one readiness view across profile, trust, and conversion signals tied to their real location.",
    problems: ["Service categories and specialties are unclear.", "Hours and contact channels drift across platforms.", "Trust proof is weak compared to nearby shops."],
    scanChecks: ["Local profile consistency and discovery signals.", "Website trust and conversion readiness checks.", "Public review and social proof indicators."],
    baseImprovements: ["Monthly readiness monitoring and summaries.", "Trend tracking for visibility and trust movement."],
    proAutomations: ["More frequent checks plus queue-based execution support.", "Expanded automation layer where available."],
    discoveryNotes: ["Google profile signals drive near-me auto intent.", "Website trust improves call confidence.", "AI summaries reward specific, corroborated shop details."],
    guideLinks: baseGuideLinks,
  },
  "apartment-complexes": {
    slug: "apartment-complexes",
    parentSlug: "property-venues",
    name: "Apartment complexes",
    metaTitle: "Local SEO for apartment complexes and leasing teams | GravyBlock",
    metaDescription: "Apartment communities can improve tours and lease inquiries with stronger profile trust and website conversion clarity.",
    h1: "Apartment complexes: improve local leasing visibility and tour conversion",
    intro: "Renters compare communities quickly using maps, reviews, photos, and website trust signals.",
    fit: "GravyBlock helps apartment operators align public facts, trust cues, and conversion paths so prospects see a consistent leasing story.",
    problems: ["Amenities and fees are inconsistent across pages.", "Tour CTAs and forms create unnecessary friction.", "Review and trust context does not match leasing reality."],
    scanChecks: ["Profile and listing consistency checks.", "Website trust and conversion checks.", "Reputation and social discovery signal patterns."],
    baseImprovements: ["Monthly readiness checks and summaries.", "Trend visibility for trust and conversion drift."],
    proAutomations: ["Faster checks and queue-based support.", "Expanded automation workflows where supported."],
    discoveryNotes: ["Google profile quality affects tour-intent discovery.", "Website trust clarity impacts lease inquiry quality.", "AI summaries draw from consistent property facts."],
    guideLinks: [{ href: "/guides/local-seo-for-apartment-complexes", label: "Local SEO for apartment complexes" }, ...baseGuideLinks],
  },
  "property-managers": {
    slug: "property-managers",
    parentSlug: "property-venues",
    name: "Property managers",
    metaTitle: "Local visibility for property management companies | GravyBlock",
    metaDescription: "Property managers can improve local trust, owner lead quality, and profile consistency with GravyBlock.",
    h1: "Property managers: strengthen local trust for owner and resident leads",
    intro: "Property management buyers expect professionalism, responsiveness, and credibility before first contact.",
    fit: "GravyBlock helps property managers keep profile details, website trust, and conversion pathways aligned as operations change.",
    problems: ["Service scope is unclear between leasing and management.", "Contact and emergency pathways are hard to find.", "Online trust signals are inconsistent across channels."],
    scanChecks: ["Google profile and listing consistency.", "Website trust and conversion readiness.", "Public review and social proof signal checks."],
    baseImprovements: ["Monthly checks and monitoring summaries.", "Trend tracking to catch trust drift early."],
    proAutomations: ["Higher refresh cadence and queue support.", "Expanded ongoing workflow automation where available."],
    discoveryNotes: ["Profile clarity improves local owner-intent discovery.", "Website trust cues improve lead quality.", "AI search prefers consistent service and geography facts."],
    guideLinks: baseGuideLinks,
  },
  "gyms-fitness-studios": {
    slug: "gyms-fitness-studios",
    parentSlug: "health-wellness",
    name: "Gyms and fitness studios",
    metaTitle: "Local search visibility for gyms and fitness studios | GravyBlock",
    metaDescription: "Gyms and studios can improve local profile trust, website conversion, reviews, and AI-search discovery readiness.",
    h1: "Gyms and fitness studios: improve local discovery and membership conversion",
    intro: "Fitness buyers compare schedules, vibe, reviews, and proximity quickly. Mixed signals cost memberships.",
    fit: "GravyBlock helps fitness operators align profile details, website trust, and conversion paths into one practical readiness model.",
    problems: ["Class schedules and offers drift between channels.", "Trial and join CTAs are unclear on mobile.", "Review/social proof signals are underused."],
    scanChecks: ["Profile consistency and local discovery indicators.", "Website trust and conversion checks.", "Public reputation and social presence patterns."],
    baseImprovements: ["Monthly monitoring with actionable summaries.", "Trend tracking for visibility and conversion movement."],
    proAutomations: ["Faster refresh plus queue-oriented workflows.", "Expanded automation coverage where configured."],
    discoveryNotes: ["Google profile quality influences near-me fitness discovery.", "Website trust and CTA clarity drive joins.", "AI summaries prioritize consistent class/service facts."],
    guideLinks: baseGuideLinks,
  },
  salons: {
    slug: "salons",
    parentSlug: "health-wellness",
    name: "Salons",
    metaTitle: "Local visibility and trust signals for salons | GravyBlock",
    metaDescription: "Salons can improve local bookings with stronger profile visibility, website trust, and review-driven conversion support.",
    h1: "Salons: turn local discovery into more booked chairs",
    intro: "Salon clients compare style proof, convenience, and trust quickly across maps, social, and websites.",
    fit: "GravyBlock helps salons improve listing consistency, website conversion readiness, and reputation trust with recurring monitoring.",
    problems: ["Service menus and booking paths are inconsistent.", "Social proof does not connect to booking actions.", "Hours or location details drift over time."],
    scanChecks: ["Profile and listing consistency checks.", "Website trust and CTA friction checks.", "Review and social proof readiness signals."],
    baseImprovements: ["Monthly readiness checks and summaries.", "Trend tracking to maintain consistency."],
    proAutomations: ["Higher refresh cadence and queue support.", "Expanded workflow automation where available."],
    discoveryNotes: ["Google profile quality affects local booking intent.", "Website trust and UX improve booking completion.", "AI answers favor coherent service and location data."],
    guideLinks: baseGuideLinks,
  },
  veterinarians: {
    slug: "veterinarians",
    parentSlug: "health-wellness",
    name: "Veterinarians",
    metaTitle: "Local visibility and trust for veterinarians | GravyBlock",
    metaDescription: "Veterinary clinics can improve local discovery, trust, and appointment conversion with stronger profile and website signals.",
    h1: "Veterinarians: improve local trust before pet owners decide",
    intro: "Pet owners decide quickly under stress. Accurate profile signals and calm website trust cues are critical.",
    fit: "GravyBlock helps veterinary practices align profile details, website trust, and conversion paths while monitoring signal drift.",
    problems: ["Emergency and routine care messaging is unclear.", "Hours and service scope drift across channels.", "Website contact paths are slow on mobile."],
    scanChecks: ["Profile consistency and local discovery checks.", "Website trust and conversion readiness indicators.", "Public review and social proof patterns."],
    baseImprovements: ["Monthly readiness monitoring and summaries.", "Trend tracking for visibility and trust changes."],
    proAutomations: ["More frequent checks and queue workflows.", "Expanded automation where your setup supports it."],
    discoveryNotes: ["Google profile quality influences urgent local discovery.", "Website trust affects booking confidence.", "AI search summarizes clinics with consistent facts and proof."],
    guideLinks: baseGuideLinks,
  },
};

export const INDIVIDUAL_INDUSTRY_SLUGS = Object.keys(INDIVIDUAL_INDUSTRY_PAGES);
