/**
 * Fetches Yelp reviews via the Yelp Fusion API.
 * Auto-discovers the Yelp business ID from the business name + address/phone on first run
 * and caches it in businesses.yelpBusinessId for future syncs.
 *
 * Requires: YELP_API_KEY environment variable.
 * Free tier returns up to 3 reviews; paid "Yelp Fusion+" returns up to 50.
 */

import { eq } from "drizzle-orm";
import { getDb, businesses, businessReviews } from "@/lib/db";

export type YelpReview = {
  id: string;
  rating: number;
  text: string;
  time_created: string; // "2024-03-15 18:23:14"
  user: {
    name: string;
    image_url?: string | null;
  };
};

type YelpSearchResult = {
  businesses?: Array<{ id: string; name: string; alias: string }>;
  total?: number;
};

type YelpReviewsResult = {
  reviews?: YelpReview[];
  total?: number;
};

function yelpHeaders() {
  const key = process.env.YELP_API_KEY;
  if (!key) return null;
  return {
    Authorization: `Bearer ${key}`,
    "Content-Type": "application/json",
  };
}

/** Find a Yelp business ID by searching name + location (phone preferred). */
async function discoverYelpBusinessId(params: {
  name: string;
  phone: string | null | undefined;
  address: string | null | undefined;
}): Promise<string | null> {
  const headers = yelpHeaders();
  if (!headers) return null;

  const url = new URL("https://api.yelp.com/v3/businesses/search");

  // Phone search is more reliable when available
  if (params.phone) {
    const digits = params.phone.replace(/\D/g, "");
    const e164 = digits.startsWith("1") ? `+${digits}` : `+1${digits}`;
    url.searchParams.set("phone", e164);
  } else if (params.address) {
    url.searchParams.set("term", params.name);
    url.searchParams.set("location", params.address);
    url.searchParams.set("limit", "1");
  } else {
    return null;
  }

  try {
    const res = await fetch(url.toString(), { headers, cache: "no-store" });
    if (!res.ok) {
      console.warn("[yelp] search failed", { status: res.status });
      return null;
    }
    const json = (await res.json()) as YelpSearchResult;
    return json.businesses?.[0]?.id ?? null;
  } catch (err) {
    console.error("[yelp] discovery error", { error: String(err) });
    return null;
  }
}

/** Fetch up to 50 reviews for a known Yelp business ID. */
async function fetchYelpReviews(yelpBusinessId: string): Promise<YelpReview[]> {
  const headers = yelpHeaders();
  if (!headers) return [];

  const url = new URL(`https://api.yelp.com/v3/businesses/${encodeURIComponent(yelpBusinessId)}/reviews`);
  url.searchParams.set("limit", "50");
  url.searchParams.set("sort_by", "yelp_sort");

  try {
    const res = await fetch(url.toString(), { headers, cache: "no-store" });
    if (!res.ok) {
      console.warn("[yelp] reviews fetch failed", { status: res.status, yelpBusinessId });
      return [];
    }
    const json = (await res.json()) as YelpReviewsResult;
    return json.reviews ?? [];
  } catch (err) {
    console.error("[yelp] reviews error", { error: String(err) });
    return [];
  }
}

export type YelpSyncResult = {
  fetched: number;
  newReviews: number;
  newInserted: Array<{
    authorName: string;
    rating: number;
    text: string | null;
    suggestedReply: null; // Yelp replies generated by caller
    publishTime: Date | null;
    source: "yelp";
  }>;
};

/**
 * Sync Yelp reviews for a business.
 * Returns newly inserted reviews so the caller can generate AI replies and send emails.
 */
export async function syncYelpReviewsForBusiness(
  businessId: string,
  generateReply: (params: { businessName: string; rating: number; reviewText: string }) => Promise<string | null>,
): Promise<YelpSyncResult> {
  const db = getDb();
  if (!db) return { fetched: 0, newReviews: 0, newInserted: [] };

  const [biz] = await db
    .select({
      name: businesses.name,
      phone: businesses.phone,
      address: businesses.address,
      yelpBusinessId: businesses.yelpBusinessId,
    })
    .from(businesses)
    .where(eq(businesses.id, businessId))
    .limit(1);

  if (!biz) return { fetched: 0, newReviews: 0, newInserted: [] };

  // Auto-discover Yelp ID if we don't have it yet
  let yelpBusinessId = biz.yelpBusinessId;
  if (!yelpBusinessId) {
    yelpBusinessId = await discoverYelpBusinessId({
      name: biz.name,
      phone: biz.phone,
      address: biz.address,
    });

    if (yelpBusinessId) {
      await db.update(businesses).set({ yelpBusinessId }).where(eq(businesses.id, businessId));
      console.info("[yelp] discovered and cached Yelp ID", { businessId, yelpBusinessId });
    } else {
      console.info("[yelp] could not discover Yelp business for", { businessId });
      return { fetched: 0, newReviews: 0, newInserted: [] };
    }
  }

  const reviews = await fetchYelpReviews(yelpBusinessId);
  if (reviews.length === 0) return { fetched: 0, newReviews: 0, newInserted: [] };

  // Fetch existing Yelp review IDs for this business
  const existingIds = await db
    .select({ googleReviewId: businessReviews.googleReviewId })
    .from(businessReviews)
    .where(eq(businessReviews.businessId, businessId));

  const existingSet = new Set(existingIds.map((r) => r.googleReviewId));
  const newInserted: YelpSyncResult["newInserted"] = [];
  let newReviews = 0;

  for (const review of reviews) {
    const externalId = `yelp:${review.id}`;
    if (existingSet.has(externalId)) continue;

    const suggestedReply = review.text
      ? await generateReply({ businessName: biz.name, rating: review.rating, reviewText: review.text })
      : null;

    const publishTime = review.time_created ? new Date(review.time_created) : null;

    await db.insert(businessReviews).values({
      businessId,
      googleReviewId: externalId,
      source: "yelp",
      authorName: review.user.name,
      authorPhotoUri: review.user.image_url ?? undefined,
      rating: review.rating,
      text: review.text,
      publishTime,
      suggestedReply,
      status: "new",
    });

    newInserted.push({
      authorName: review.user.name,
      rating: review.rating,
      text: review.text ?? null,
      suggestedReply: null, // returned so caller can include in email
      publishTime,
      source: "yelp",
    });
    newReviews++;
  }

  return { fetched: reviews.length, newReviews, newInserted };
}
